language: go
go:
- tip
notifications:
  slack: cadena-monde:HlU1j8pQmAeoo5bGc8byURrr
deploy:
  provider: heroku
  buildpack: https://github.com/kr/heroku-buildpack-go.git
  api_key:
    secure: NaN/6DNtjAuUCPma+RNfP3U0xPxoK0pbr88fBXcfzb/0emf+Hh5udw7ANdydAudtZd/JE4qoPhsKW8VxQ0IjfLcjZtlofMNySqBHOtzFVngtesup8kTkgu6JVZJ9I5l83paDpF3igpUkTD9N1lnhs82Z1VzFbbyl0l0CAbr0sxk=
  app: monde-gobot
  on: master